### PR TITLE
merge into master from #27-ferry-breakfast

### PR DESCRIPTION
**Pull request by mangamon-ferry**
## Related Issue
- connect opsttan/my-site-github#27

## Modifications
- add ferry 20170608 breakfast

## Target Page
- https://opsttan.github.io/my-site-breakfast/201706.html

## Check Point
- [x] ferry's 20170608 breakfast have been added

### CODE REVIEW

**Comment by mangamon-ferry** [comment]
@opsttan 

Hi Tan,
Can you help review it? thanks :)

Regards,

Ferry

**Comment by opsttan** [comment]
@mangamon-ferry 
Hi , ferry.
Please merge new master and resolve the conflict.
Make sure your line is under mine.
Thank you.

**Comment by opsttan** [comment]
No problem.
I will merge it after Ian or Willy create their work branch.

**Comment by mangamon-ferry** [comment]
@opsttan ,

Ok Tan,thanks a lot Tan :)

Regards,

Ferry

**Review by opsttan — APPROVED** [review]

**Pull request merged**
