### PR TITLE
merge into master from #23-willy-breakfast

### PR DESCRIPTION
**Pull request by ghost**
## Related Issue
- connect opsttan/my-site-github#23

## Modifications
- add willy 20170602 breakfast

## Target Page
- https://opsttan.github.io/my-site-breakfast/Willy.html

## Check Point
- [x] willy's 20170602 breakfast have been added

### CODE REVIEW

**Comment by ghost** [comment]
@opsttan can you review my pull request, thankyou

**Comment by opsttan** [comment]
@mangamon-willy 
No problem here!
Now please merge new master to your work branch and push it.

**Comment by ghost** [comment]
@opsttan , i already merge new master to my work branch, and also has push it , please review it, thanks

**Review by opsttan — APPROVED** [review]

**Comment by opsttan** [comment]
@mangamon-willy 
look good to me.
Thank you for your work.

**Pull request merged**
