### PR TITLE
merge into master from #24-ferry-breakfast

### PR DESCRIPTION
**Pull request by mangamon-ferry**
## Related Issue
- connect opsttan/my-site-github#24

## Modifications
- add ferry 20170605 breakfast

## Target Page
- https://opsttan.github.io/my-site-breakfast/Ferry.html

## Check Point
- [ ] ferry's 20170605 breakfast have been added

### CODE REVIEW

**Comment by mangamon-ferry** [comment]
@opsttan 

Hi Tan,

Can you Review it? thanks :)

Regards,

Ferry

**Comment by opsttan** [comment]
@mangamon-ferry 
Hi ,ferry.

Seems like you didn't create your work branch from new master.
You create it from old master( ebc271a ) , fetch&pull new master , merge it , then modify your breakfast file.
Am I right?

I know you want to practice merge at the same time, but in that case, your commit log will be very complicated.
image

You only committed once ,but there are 3 commit log for it.

Since you already understood how to merge something to your work branch.
I will look through it this time.

But please notice that sometimes it will occur a problem.

Now please merge new master again.

**Comment by mangamon-ferry** [comment]
@opsttan 

@opsttan 
hi Tan,

Actually i already pull from remote master before i'm create my branch, but i will make the pull again one more time, maybe there is an error when i'm pull from remote master :)

Regards,

Ferry

**Comment by mangamon-ferry** [comment]
@tan

Hi Tan,

I thin my Source Tree have an error, i;m trying to fix it first,  :)

Regards,

Ferry

**Comment by opsttan** [comment]
@mangamon-ferry 

>Actually i already pull from remote master before i'm create my branch, but i will make the pull again one more time, maybe there is an error when i'm pull from remote master :)

Maybe you forgot use fetch first?
Anyway you don't need to fix it this time, it's very complicated.
If you really want to handle it , you can do like this.
1. close this pull request.
2. delete your remote work branch.
3. delete your local work branch.
4. create work branch from new master again.
5. modify your breakfast file.
6. create new pull request.

**Pull request closed without merging**
