### PR TITLE
merge into master from #24-Ian-breakfast

### PR DESCRIPTION
**Pull request by mangamon-ian**
## Related Issue
- connect opsttan/my-site-github#24

## Modifications
- add Ian 20170603 breakfast
- add Ian 20170604 breakfast
- add Ian 20170605 breakfast

## Target Page
- https://opsttan.github.io/my-site-breakfast/Ian.html

## Check Point
- [x] Ian's 20170603 breakfast have been added
- [x] Ian's 20170604 breakfast have been added
- [x] Ian's 20170605 breakfast have been added

### CODE REVIEW

**Comment by mangamon-ian** [comment]
OK @opsttan !
I already create a  new pull request for today.
Looking forward for our conflict management tutorial.

**Comment by opsttan** [comment]
@mangamon-ian 
LGTM.
Now please merge new master to your work branch then push it.

**Comment by mangamon-ian** [comment]
@opsttan 
Roger!
Already pulled the new master, merge it again with new work branch, and push it again.

Thanks

**Review by opsttan — APPROVED** [review]

**Comment by opsttan** [comment]
@mangamon-ian 
LGTM.
Thank you for your work.

**Pull request merged**
