### PR TITLE
merge into master from #26-willy-breakfast

### PR DESCRIPTION
**Pull request by ghost**
## Related Issue
- connect opsttan/my-site-github#26

## Modifications
- add willy 20170607 breakfast

## Target Page
- https://opsttan.github.io/my-site-breakfast/201706.html

## Check Point
- [ ] willy's 20170607 breakfast have been added

### CODE REVIEW

**Comment by ghost** [comment]
@opsttan , morning, i already create the pull request, please review it, thank you

**Comment by opsttan** [comment]
@mangamon-willy 
Hi Willy, I merged Willy's branch first to let you get conflict.
Now please merge new master to your work branch and resolve conflict , thank you .

**Comment by ghost** [comment]
@opsttan , i already merge the new master, please review it, thanks

**Comment by ghost** [comment]
@opsttan , i already resolve the conflict, please review it, thanks

**Comment by opsttan** [comment]
LGTM.

**Review by opsttan — APPROVED** [review]

**Pull request merged**
