### PR TITLE
merge into master from #21-ian-breakfast

### PR DESCRIPTION
**Pull request by mangamon-ian**
## Related Issue
- connect opsttan/my-site-github#21

## Modifications
- add Ian 20170529 breakfast to "Ian.html"
- add Ian 20170530 breakfast to "Ian.html"

## Target Page
- https://opsttan.github.io/my-site-breakfast/Ian.html

## Check Point
- [x] Ian's 20170529 breakfast have been added
- [x] Ian's 20170530 breakfast have been added

### CODE REVIEW

**Comment by mangamon-ian** [comment]
@opsttan , is this procedure already right?

If this one is okay, please merge my html file from my branch to master.
Thank you!

PS: I will remove my local repo to C;/github

**Comment by opsttan** [comment]
@mangamon-ian 
Thank you for your work.
Modification is right.
But still have some little problems at this pull request.
No.1 Title
No.2 Contents under the `Related Issue`

You can take a look at [Ferry's PR](https://github.com/opsttan/my-site-breakfast/pull/1).

**Comment by mangamon-ian** [comment]
Hi @opsttan .
I updated the title and content under related issue once again, following Mr Ferry's work.
I hope this one is right now

**Comment by opsttan** [comment]
@mangamon-ian 
Well.... Very close, but still have one problem.
Your pull request title is `merge into master from #21-adding-Ian's-breakfast` , but your work branch is `#21-ian-breakfast` .
Please modify it again.

**Comment by mangamon-ian** [comment]
ooohhh .... I see
I have changed the title once again, @opsttan 
Now the title of this pull request is the same with my branch

**Review by opsttan — APPROVED** [review]

**Comment by opsttan** [comment]
@mangamon-ian 
Thank you for your work.

**Pull request merged**
