### PR TITLE
merge into master from #21-ferry_modify-breakfast

### PR DESCRIPTION
**Pull request by mangamon-ferry**
## Related Issue
- connect opsttan/my-site-github#21

## Modifications
- add content “ferry.html” “20170529”

## Target Page
- https://opsttan.github.io/my-site-breakfast/Ferry.html

## Check Point
- [x] ferry’s breakfast content's 20170529 have been added

### CODE REVIEW

**Comment by opsttan** [comment]
@mangamon-ferry 
①
It's looks like a restaurant menu.
I want you write your today's breakfast only.
Like this one.
https://opst-fujimoto.github.io/my-site-github/morning/tan.html
②
Your `Target Page` can't open.
Please check upper case letter.

**Comment by mangamon-ferry** [comment]
Related Issue
connect opsttan/my-site-github#21

Modifications
add content “Ferry.html” “20170529”

Target Page
https://opsttan.github.io/my-site-breakfast/Ferry.html

Check Point
 ferry’s breakfast content's 20170529 Revision

**Comment by opsttan** [comment]
@mangamon-ferry 
Thank you for your work!
Still have some little problem here.

①
Please refer to the following pull request title, and modify this pull request.
https://github.com/opsttan/my-site-github/pull/20
②
After you finish your work, please mention reviewer on the comment.
Otherwise, reviewer may not notice it.
③
This comment won't be necessary.
https://github.com/opsttan/my-site-breakfast/pull/1#issuecomment-304615197

**Comment by opsttan** [comment]
@mangamon-ferry 

I'm not a native speaker.
Sorry to have confused you.
Let me explain.

>①
Please refer to the following pull request title, and modify this pull request.
opsttan/my-site-github#20

Please click opsttan/my-site-github#20 , you can see pull request title looks like ` merge into master from {work branch name}` right?
Your pull request title is `connect opsttan/my-site-github#21` , please modify it to `merge into master from {work branch name}` .

>②
After you finish your work, please mention reviewer on the comment.
Otherwise, reviewer may not notice it.

After you finished your work, you only assigned to me.
In that case, reviewer won't know you have done it or not.
So, just comment on your pull request to let me notice that.
image
And you can click [here](https://github.com/blog/821-mention-somebody-they-re-notified) to check about how to mention someone.

>③
This comment won't be necessary.
https://github.com/opsttan/my-site-breakfast/pull/1#issuecomment-304615197

I've noticed that you add [this comment](https://github.com/opsttan/my-site-breakfast/pull/1#issuecomment-304615197) on this pull reuqest.
What's it for?
You already wrote the same thing on the top of this page.
Please delete the comment.
image

**Comment by mangamon-ferry** [comment]
@opsttan 
Hi Tan, 
Is it correct now? thanks :)

**Review by opsttan — APPROVED** [review]

**Comment by opsttan** [comment]
@mangamon-ferry 
Thank you for your work.

**Pull request merged**
