### PR TITLE
merge into master from #28-willy-breakfast

### PR DESCRIPTION
**Pull request by ghost**
## Related Issue
- connect opsttan/my-site-github#28

## Modifications
- add willy 20170609 breakfast

## Target Page
- https://opsttan.github.io/my-site-breakfast/201706.html

## Check Point
- [x] willy's 20170609 breakfast have been added

### CODE REVIEW

**Comment by opsttan** [comment]
@mangamon-willy 
no problem.
please merge new master and resolve conflict.

**Comment by ghost** [comment]
@opsttan , i already create a pull request,please review it, thanks

**Comment by opsttan** [comment]
please merge new master and resolve conflict.

**Comment by ghost** [comment]
@opsttan , i already push the commit, please review it, thank you @opsttan

**Comment by opsttan** [comment]
no problem.

**Review by opsttan — APPROVED** [review]

**Pull request merged**
