### PR TITLE
merge into master from #23-ferry-breakfast

### PR DESCRIPTION
**Pull request by mangamon-ferry**
## Related Issue
- connect opsttan/my-site-github#23

## Modifications
- add ferry 20170602 breakfast

## Target Page
- https://opsttan.github.io/my-site-breakfast/Ferry.html

## Check Point
- [ ] ferry's 20170602 breakfast have been added

### CODE REVIEW

**Comment by mangamon-ferry** [comment]
@opsttan 

Hi tan,

Can you review it? thanks :)

Regards,

Ferry

**Comment by opsttan** [comment]
@mangamon-ferry 
No problem here!
Now please merge new master to your work branch.

**Comment by mangamon-ferry** [comment]
@opsttan 

Hi Tan, i already merge master to my local branch and push it too, and the status is already up to date :)

Regards,

Ferry

**Comment by opsttan** [comment]
@mangamon-ferry 
Have you pushed your work branch again?
I can't see it

**Comment by opsttan** [comment]
If you already did that ,the graph will be like this.
image

**Comment by mangamon-ferry** [comment]
@opsttan 

Sorry take a long time, i already pushed my work branch, is it correct Tan? :)

Regards,

Ferry

**Review by opsttan — APPROVED** [review]

**Comment by opsttan** [comment]
@mangamon-ferry 
look good to me!
Thank you for your work

**Pull request merged**
