### PR TITLE
merge into master from #22-ferry-breakfast

### PR DESCRIPTION
**Pull request by mangamon-ferry**
## Related Issue
- connect opsttan/my-site-github#22

## Modifications
- add contents for ferry breakfast “ferry.html” “20170531”

## Target Page
- https://opsttan.github.io/my-site-breakfast/Ferry.html

## Check Point
- [x] ferry’s breakfast content's 20170531 have been added

### CODE REVIEW

**Comment by opsttan** [comment]
@mangamon-ferry 
Thank you for your quick work.
Please check the following pointing out.

No.1
Where is your breakfast today?
I only find out 5/29 and 5/30 breakfast.

No.2
I've noticed that you already moved unnecessary spaces here.
Sorry to make you confuse.
But what I mean is you need to compare with your last version.
you can check it [here](https://github.com/opsttan/my-site-breakfast/pull/4/files).
image
You can see so many diffs here which make reviewer hard to review it.
About unnecessary spaces , please forget it now.
Next time would be fine.

No.3
It's better to create pull request first , then mention the reviewer on the comment.

**Comment by mangamon-ferry** [comment]
@opsttan 
Hi Tan,

i Already revised the content, can you review it? Thanks a lot Tan :)

**Comment by opsttan** [comment]
@mangamon-ferry 
Seems like everything is fine except the last row.
image
It should not display as a diff here. :)

**Comment by mangamon-ferry** [comment]
@opsttan 

Hi Tan,

I already added new line at the last row :)

**Review by opsttan — APPROVED** [review]

**Comment by opsttan** [comment]
@mangamon-ferry 
thank you for your work.

**Pull request merged**
